# Generated by Django 5.2.4 on 2025-08-03 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menucategory_menufood_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menufood',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='category_name', to='restaurant.menucategory'),
        ),
    ]
