# Generated by Django 5.2.4 on 2025-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_drinkscategory_drinks_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menufood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
