# Generated by Django 5.2.4 on 2025-08-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='no_subject', max_length=200),
            preserve_default=False,
        ),
    ]
