# Generated by Django 5.2.4 on 2025-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='category_id',
        ),
        migrations.AddField(
            model_name='drinks',
            name='categories',
            field=models.ManyToManyField(blank=True, to='restaurant.drinkscategory'),
        ),
    ]
