# Generated by Django 5.2.4 on 2025-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_remove_drinks_category_id_drinks_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
