# Generated by Django 5.2.4 on 2025-08-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_reservation_is_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_shared',
        ),
    ]
