# Generated by Django 5.2.4 on 2025-08-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_remove_reservation_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='allows_shared',
            field=models.BooleanField(default=False, help_text='True means shared, False is private only.'),
        ),
    ]
