# Generated by Django 5.2.4 on 2025-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_alter_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
