# Generated by Django 5.2.4 on 2025-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='description',
            field=models.TextField(default='describe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drinks_images/'),
        ),
    ]
